-- Tenants and their API credentials (ADR 0001).
-- Ids are generated by the application, not by database defaults.

CREATE TABLE tenants (
    id          uuid        PRIMARY KEY,
    name        text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
    id            uuid        PRIMARY KEY,
    tenant_id     uuid        NOT NULL REFERENCES tenants (id),
    -- Public lookup handle embedded in the presented key: dbk_<key_id>_<secret>.
    key_id        text        NOT NULL,
    -- SHA-256 of the secret part. The plaintext secret is never stored.
    secret_hash   text        NOT NULL,
    status        text        NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_used_at  timestamptz,

    CONSTRAINT api_keys_key_id_key UNIQUE (key_id),
    CONSTRAINT api_keys_status_check CHECK (status IN ('ACTIVE', 'REVOKED'))
);

CREATE INDEX api_keys_tenant_id_idx ON api_keys (tenant_id);
